apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../base

namespace: quizapp-wip-cicd
nameSuffix: -wip-cicd

images:
- name: quizapp-image-name
  newName: /quizapp
  newTag: wip-cicd-ab29c365

configMapGenerator:
- behavior: create
  envs:
  - environment-variables.env
  name: environment-variables
- behavior: create
  literals:
  - NAME=quizapp-wip-cicd
  name: namespace
- literals:
  - NAME=docker-registry-cred-quizapp-wip-cicd
  name: registry-secrets

replacements:
- source:
    fieldPath: data.NAME
    kind: ConfigMap
    name: namespace
  targets:
  - fieldPaths:
    - metadata.name
    select:
      kind: Namespace
- source:
    fieldPath: data.NAME
    kind: ConfigMap
    name: registry-secrets
  targets:
  - fieldPaths:
    - spec.template.spec.imagePullSecrets.0.name
    select:
      kind: Deployment
- source:
    fieldPath: data.INGRESS_CLASS_NAME
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.ingressClassName
    select:
      kind: Ingress
- source:
    fieldPath: data.INGRESS_TLS_HOST
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    select:
      kind: Ingress
- source:
    fieldPath: data.INGRESS_TLS_SECRETNAME
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
- source:
    fieldPath: data.INGRESS_HOST
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.rules.0.host
    select:
      kind: Ingress
