apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../base

namespace: quizapp-dev
nameSuffix: -dev

images:
- name: quizapp-image-name
  newName: 10.96.55.55:5000/quizapp
  newTag: dev-09bd0416

configMapGenerator:
- behavior: create
  envs:
  - environment-variables.env
  name: environment-variables
- behavior: create
  literals:
  - NAME=quizapp-dev
  name: namespace
- literals:
  - NAME=docker-registry-cred-quizapp-dev
  name: registry-secrets

#- source:
#    kind: ConfigMap
#    name: environment-variables
#    fieldPath: data.CERT_MANAGER_ISSUER
#  targets:
#  - select:
#      kind: Ingress
#    fieldPaths: 
#    - "metadata.annotations.[cert-manager.io/issuer]"
#- source:
#    kind: ConfigMap
#    name: environment-variables
#    fieldPath: data.INGRESS_TLS_SECRETNAME
#  targets:
#  - select:
#      kind: Ingress
#    fieldPaths: 
#    - "spec.tls.0.secretName"
replacements:
- source:
    fieldPath: data.NAME
    kind: ConfigMap
    name: namespace
  targets:
  - fieldPaths:
    - metadata.name
    select:
      kind: Namespace
- source:
    fieldPath: data.NAME
    kind: ConfigMap
    name: registry-secrets
  targets:
  - fieldPaths:
    - spec.template.spec.imagePullSecrets.0.name
    select:
      kind: Deployment
- source:
    fieldPath: data.INGRESS_CLASS_NAME
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.ingressClassName
    select:
      kind: Ingress
- source:
    fieldPath: data.INGRESS_TLS_HOST
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.tls.0.hosts.0
    select:
      kind: Ingress
- source:
    fieldPath: data.INGRESS_HOST
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.rules.0.host
    select:
      kind: Ingress
